name: nodejs test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['latest']

    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: latest

    - name: install
      #run: pnpm ci # needs package-lock.json
      run: pnpm install

    - name: build
      run: pnpm run --if-present build

    - name: test
      run: pnpm run test
